import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { LoadingSpinner } from './LoadingSpinner';
import { explainAssignment } from '@/lib/auth';
import { useToast } from '@/hooks/use-toast';
import { BookOpen, Lightbulb, X } from 'lucide-react';

interface ExplanationModalProps {
  isOpen: boolean;
  onClose: () => void;
  assignmentId: string | null;
  assignmentTitle?: string;
}

export const ExplanationModal: React.FC<ExplanationModalProps> = ({
  isOpen,
  onClose,
  assignmentId,
  assignmentTitle
}) => {
  const [explanation, setExplanation] = useState<string>('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    if (isOpen && assignmentId) {
      fetchExplanation();
    }
  }, [isOpen, assignmentId]);

  const fetchExplanation = async () => {
    if (!assignmentId) return;
    
    setIsLoading(true);
    setExplanation('');
    
    try {
      const result = await explainAssignment(assignmentId);
      setExplanation(result.explanation);
    } catch (error: any) {
      toast({
        title: "Failed to get explanation",
        description: error.message || "Could not fetch assignment explanation.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleClose = () => {
    setExplanation('');
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl max-h-[80vh] shadow-glow">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <Lightbulb className="w-6 h-6 text-primary" />
            Assignment Explanation
          </DialogTitle>
          {assignmentTitle && (
            <DialogDescription className="flex items-center gap-2 text-base">
              <BookOpen className="w-4 h-4" />
              {assignmentTitle}
            </DialogDescription>
          )}
        </DialogHeader>

        <ScrollArea className="max-h-[60vh] pr-4">
          {isLoading ? (
            <div className="flex items-center justify-center py-12">
              <div className="text-center">
                <LoadingSpinner size="lg" className="text-primary mx-auto mb-4" />
                <p className="text-muted-foreground">
                  Generating personalized explanation...
                </p>
              </div>
            </div>
          ) : explanation ? (
            <div className="space-y-4">
              <div className="bg-gradient-card p-6 rounded-lg border shadow-soft">
                <div className="prose prose-sm max-w-none">
                  {explanation.split('\n').map((paragraph, index) => (
                    paragraph.trim() && (
                      <p key={index} className="mb-3 text-foreground leading-relaxed">
                        {paragraph}
                      </p>
                    )
                  ))}
                </div>
              </div>
              
              <div className="bg-accent/20 p-4 rounded-lg border border-accent/30">
                <p className="text-sm text-accent-foreground font-medium">
                  💡 This explanation was generated by your AI education assistant to help you understand the assignment better.
                </p>
              </div>
            </div>
          ) : (
            <div className="text-center py-12">
              <BookOpen className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
              <p className="text-muted-foreground">
                No explanation available for this assignment.
              </p>
            </div>
          )}
        </ScrollArea>

        <div className="flex justify-end pt-4 border-t">
          <Button variant="education" onClick={handleClose}>
            <X className="w-4 h-4 mr-2" />
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};